name: tango_calendar
description: Tango Calendar

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  dio: ^5.1.1
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  html: ^0.15.2
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/users/default.png

  fonts:
    - family: Shrikhand
      fonts:
        - asset: assets/fonts/Shrikhand-Regular.ttf
    - family: Mate
      fonts:
        - asset: assets/fonts/MateSC-Regular.ttf
    - family: Frederic
      fonts:
        - asset: assets/fonts/FrederickatheGreat-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
